---
apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: chatbot-assets
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{image}}:{{tag}}
  team: {{team}}
  port: 8080
  ingresses:
    - https://www.nav.no/person/chatbot-assets
  liveness:
    path: /person/chatbot-assets/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/chatbot-assets/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      cpu: '3'
      memory: 768Mi
    requests:
      memory: 512Mi
