version: 2.1

jobs:
  
  build:
    docker:
      - image: circleci/node:10 # the primary container, where your job's commands are run
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1
      - run:
          name: Bygg react app
          command: |
            npm ci && npm run build
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Tester
          command: npm run test
      
  deploy-til-dev:
    docker:
      - image: circleci/python:3.7-stretch
    working_directory: ~/build
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3 dev bucket
          command: aws s3 sync . s3//personopplysningerdev --delete


  deploy-til-prod:

workflows:
  bygg_og_deploy:
    jobs:
      - build
      - deploy-til-dev:
          requires:
            - build:
          filters:
            branches:
              only: aws