version: 2.1

jobs:
  
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Installer npm pakker
          command: |
            npm ci
      - run:
          name: Bygg React App
          command: |
            PUBLIC_URL=$CIRCLE_BUILD_NUM npm run build
      - run:
          name: Lag mappestruktur for deploy
          command: |
            mkdir folder_to_persist
            cp build/index.html folder_to_persist/
            mkdir $CIRCLE_BUILD_NUM
            mv build/* $CIRCLE_BUILD_NUM/
            mv $CIRCLE_BUILD_NUM build/
            mv build folder_to_persist/
      - run:
          name: Tester
          command: npm run test
      - persist_to_workspace:
          root: folder_to_persist
          paths: ./*
  
  deploy-til-dev:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - attach_workspace:
          at: folder_to_persist/
      - run: 
          name: deploy til '$web'-container
          command: |
              find ./folder_to_persist/build/ -type f -exec curl -I -X PUT -T {}  -H "x-ms-date: $(date -u)" -H "x-ms-blob-type: BlockBlob" "https://testblobfortest.blob.core.windows.net/test/{}?sv=$AZURE_STORAGE_SAS" \;
              # az storage blob delete-batch -s '$web' --account-name sapersonopplysninger
              # az storage blob upload-batch -d '$web' --account-name sapersonopplysninger -s folder_to_persist/build/
              # az storage blob upload -c '$web' -f folder_to_persist/index.html -n index.html --account-name sapersonopplysninger
      # - run:
      #     name: deploy til cdn-container
      #     command: |
      #         az storage blob upload-batch -d sc-personopplysninger --account-name sapersonopplysninger -s folder_to_persist/build/
      #         az storage blob upload -c sc-personopplysninger -f folder_to_persist/index.html -n index.html --account-name sapersonopplysninger

  purge-cdn:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - attach_workspace:
          at: build/
      - run: 
          name: Installer og autentiser az cli
          command: |
              curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
              az login --service-principal -u bb1f59d6-e80f-4e18-96cf-6813b13ed22c -p $AZURE_CLIENT_SECRET --tenant 966ac572-f5b7-4bbe-aa88-c76419c0f851
      - run:
          name: purge cdn
          command: |
              az cdn endpoint purge -g rg-personopplysninger -n personopplysninger-q --profile-name cdn-personopplysninger --content-paths /index.html
              az cdn endpoint purge -g rg-personopplysninger -n personopplysninger-function --profile-name cdn-personopplysninger --content-paths /api/dekorator

workflows:
  bygg-og-deploy:
    jobs:
      - build
      # - bekreft-deploy:
      #     type: approval
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #           only: azure
      - deploy-til-dev:
          name: deploy-til-dev
          # requires:
          #   - bekreft-deploy
      # - purge-cdn:
      #     requires:
      #       - deploy-til-dev
