version: 2.1

jobs:
  
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1
      - run:
          name: Bygg react app
          command: |
            npm ci && npm run build
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Tester
          command: npm run test
      - persist_to_workspace:
          root: build
          paths: ./*
  
  deploy-til-dev:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - attach_workspace:
          at: build/
      - add_ssh_keys:
          fingerprints:
           - "c1:0a:7f:22:13:8c:5b:47:54:c3:10:85:cb:59:8d:ee"
      - run:
          name: Create package.json
          command: |
            npm i firebase-tools
      - run:
          name: Clone firebase-hosting
          command: |
            git clone git@github.com:navikt/firebase-hosting.git
      - run:
          name: Move build-contents into firebase-hosting/public
          command: | 
            rm -r firebase-hosting/public/*
            mv build/* firebase-hosting/public
      - run:
          name: Deploy to Firebase
          command: |
            cd firebase-hosting
            ../node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
  

workflows:
  bygg_og_deploy:
    jobs:
      - build
      # Legg til deploy-til-dev-manuelt
      - deploy-til-dev:
          requires:
            - build