version: 2.1

jobs:
  
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1
      - run:
          name: Bygg react app
          command: |
            npm ci && PUBLIC_URL=$CIRCLE_TAG npm run build
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Tester
          command: npm run test
      - persist_to_workspace:
          root: build
          paths: ./*
  
  deploy-til-dev:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - attach_workspace:
          at: build/
      - run: 
          name: Install and authenticate az cli
          command: |
              curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
              az login --service-principal -u bb1f59d6-e80f-4e18-96cf-6813b13ed22c -p $AZURE_CLIENT_SECRET --tenant 966ac572-f5b7-4bbe-aa88-c76419c0f851
      - run:
          name: deploy to Azure container
          command: |
              az storage blob upload-batch -d sc-personopplysninger/$CIRCLE_TAG --account-name sapersonopplysninger -s build/
  

workflows:
  bygg-og-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy-til-dev:
          name: automatisk-deploy-til-dev
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
