version: 2.1

jobs:
  
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1
      - run:
          name: Bygg react app
          command: |
            npm ci && npm run build
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Tester
          command: npm run test
      - persist_to_workspace:
          root: build
          paths: ./*
  
  deploy-til-dev:
    docker:
      - image: circleci/node:10
    steps:
      - add_ssh_keys:
          fingerprints:
           - "68:53:8d:58:a1:13:1e:b2:57:88:cc:65:d6:43:76:d3"
      - run:
          name: Clone gcp-serverless
          command: |
            ssh -o StrictHostKeyChecking=no github.com exit
            git clone git@github.com:navikt/gcp-serverless.git && cd gcp-serverless
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
  


workflows:
  bygg_og_deploy:
    jobs:
      - build
      # Legg til deploy-til-dev-manuelt
      - deploy-til-dev:
          requires:
            - build