version: 2.1

jobs:
  
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1
      - run:
          name: Bygg react app
          command: |
            npm ci && npm run build
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Tester
          command: npm run test
      - persist_to_workspace:
          root: build
          paths: ./*

  deploy-til-dev:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - attach_workspace:
          at: build/
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3 dev bucket
          command: aws s3 sync ./build s3://personopplysningerdev --delete

  deploy-til-prod:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Deploy to S3 prod bucket.
          command: aws s3 sync s3://personopplysningerdev s3://personopplysningerprod --delete


workflows:
  bygg_og_deploy:
    jobs:
      - build
      - deploy-til-dev:
          requires:
            - build
          filters:
            branches:
              only: aws
      - deploy-til-prod:
          requires:
            - deploy-til-dev
                filters:
                  tags:
                    only: /^v.*/
                  branches:
                    ignore: /.*/
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
            
          
