version: 2.1

jobs:
  
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - node-v1-{{ .Branch }}-
            - node-v1
      - run:
          name: Bygg react app
          command: |
            npm ci && npm run build
      - save_cache:
          paths:
            - ~/usr/local/lib/node_modules # location depends on npm version
          key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Tester
          command: npm run test
      - persist_to_workspace:
          root: build
          paths: ./*
  
  deploy-til-dev:
    docker:
      - image: circleci/node:10
    steps:
      - attach_workspace:
          at: build/
      - add_ssh_keys:
          fingerprints:
           - "17:aa:6e:76:27:f5:bf:4a:81:f3:cb:7a:27:63:c1:19"
      - run:
          name: Create package.json
          command: |
            npm i firebase-tools
      - run:
          name: Clone gcp-serverless
          command: |
            git clone git@github.com:navikt/gcp-serverless.git
      - run:
          name: Deploy to Firebase
          command: firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
  


workflows:
  bygg_og_deploy:
    jobs:
      - build
      # Legg til deploy-til-dev-manuelt
      - deploy-til-dev:
          requires:
            - build