name: Deploy to dev-sbs
on:
  push:
    tags:
      - v*-dev
jobs:
  deploy:
    name: Deploy til dev-sbs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Define environment variables
        run: |
          echo ::set-env name=IMAGE_REGISTRY::docker.pkg.github.com
          echo ::set-env name=IMAGE_VERSION::$(echo ${GITHUB_REF:10})
          echo ::set-env name=IMAGE_NAME::$(echo ${GITHUB_REPOSITORY})
      - name: Build docker image
        run: |
          echo $GITHUB_TOKEN | docker login $IMAGE_REGISTRY -u "x-access-token" --password-stdin
          docker build -t $IMAGE_NAME:$IMAGE_VERSION .
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push docker image
        run: |
          docker push $REGISTRY/$IMAGE_NAME:$IMAGE_VERSION
      - name: Define variables for navikt/deployment-cli
        run: |
          echo $IMAGE_NAME > .docker_image
          echo $IMAGE_VERSION > .docker_tag
      - name: Deploy
        uses: navikt/deployment-cli/action@0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: dev-sbs
          team: personbruker
          resources: .nais/config.dev.yaml
