name: Deploy to q2
on:
  push:
    tags:
      - v*-dev
jobs:
  deploy:
    name: Deploy til q2
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Define build environment
        run: |
          echo ::set-env name=VERSION::$(echo ${GITHUB_REF:10})
          echo ::set-env name=IMAGE::$(echo ${GITHUB_REPOSITORY})
      - name: Define client-side environment
        run: |
          echo ::set-env name=REACT_APP_MILJO::q2
          echo ::set-env name=REACT_APP_BASE_URL::https://www-q2.nav.no
          echo ::set-env name=REACT_APP_APP_URL::https://www-q2.nav.no/person/personopplysninger
          echo ::set-env name=REACT_APP_API_URL::https://www-q2.nav.no/person/personopplysninger-api
          echo ::set-env name=REACT_APP_DSOP_URL::https://www-q2.nav.no/person/dsop-api
          echo ::set-env name=REACT_APP_TJENESTE_URL::https://tjenester-q2.nav.no
          echo ::set-env name=REACT_APP_LOGIN_URL::https://loginservice-q.nav.no/login
          echo ::set-env name=REACT_APP_LOGOUT_URL::https://loginservice-q.nav.no/slo
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm build
      - name: Build docker image
        run: |
          echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker build -t $IMAGE:$VERSION .
      - name: Push docker image
        run: docker push $IMAGE:$VERSION
      - name: Define variables for navikt/deployment-cli
        run: |
          echo $IMAGE > .docker_image
          echo $VERSION > .docker_tag
      - name: Deploy
        uses: navikt/deployment-cli/action@0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: dev-sbs
          team: personbruker
          resources: .nais/config.dev.yaml
