name: Deploy to dev-sbs
on: [push]
jobs:
  build:
    name: Build react app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build --if-present
      - run: npm test --if-present

  deploy:
    name: Deploy til dev-sbs
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Define environment variables
        run: |
          echo ::set-env name=IMAGE_REGISTRY::docker.pkg.github.com
          echo ::set-env name=IMAGE_VERSION::$(echo ${GITHUB_SHA})
          echo ::set-env name=IMAGE_NAME::$(echo ${GITHUB_REPOSITORY})
      - name: Build docker image
        run: |
          echo $GITHUB_TOKEN | docker login $IMAGE_REGISTRY -u "x-access-token" --password-stdin
          docker build -t $IMAGE_NAME:$IMAGE_VERSION .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push docker image
        run: |
          docker push $IMAGE_NAME:$IMAGE_VERSION
      - name: Define variables for navikt/deployment-cli
        run: |
          echo $IMAGE_NAME > .docker_image
          echo $IMAGE_VERSION > .docker_tag
      - name: Deploy
        uses: navikt/deployment-cli/action@0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          cluster: dev-sbs
          team: personbruker
          resources: .nais/config.dev.yaml
